import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin, getOrgId } from '@/lib/supabase'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    let orgId = await getOrgId(req)
    
    // Allow internal webhook routing to bypass cookie auth
    if (!orgId && req.headers.get('x-internal-secret') === (process.env.N8N_WEBHOOK_SECRET || 'internal-ai-reply')) {
      orgId = body.org_id
    }

    if (!orgId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { conversation_id, phone_number, message, media_url, media_type } = body

    if (!conversation_id || !phone_number) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const timestamp = new Date().toISOString()

    // Fetch conversation platform
    const { data: conv } = await supabaseAdmin
      .from('conversations')
      .select('platform')
      .eq('id', conversation_id)
      .eq('org_id', orgId)
      .maybeSingle()
    const platform = conv?.platform || 'whatsapp'

    // 1. Save outgoing message
    const { data: msg, error: msgError } = await supabaseAdmin
      .from('messages')
      .insert({
        conversation_id,
        org_id: orgId,
        phone_number,
        message: message || '',
        direction: 'outgoing',
        timestamp,
        media_url: media_url || null,
        media_type: media_type || null,
        platform,
      })
      .select()
      .single()

    if (msgError) throw msgError

    // 2. Update conversation
    await supabaseAdmin
      .from('conversations')
      .update({ 
        last_message: message || (media_type?.startsWith('image') ? '📸 Image' : '📎 Attachment'), 
        updated_at: timestamp
      })
      .eq('id', conversation_id)
      .eq('org_id', orgId)

    // 3. Fetch Delivery Settings (Meta Native or n8n Fallback)
    const { data: settings } = await supabaseAdmin
      .from('organization_settings')
      .select('n8n_reply_webhook_url, whatsapp_token, whatsapp_phone_id')
      .eq('org_id', orgId)
      .single()

    const { whatsapp_token, whatsapp_phone_id, n8n_reply_webhook_url } = settings || {}

    // Priority 1: Native Meta/WhatsApp Cloud API
    if (whatsapp_token && whatsapp_phone_id) {
      console.log(`[reply] Sending natively via WhatsApp Cloud API for org: ${orgId}`)
      
      let determinedType = media_url ? media_type?.split('/')[0] : 'text'
      
      // WhatsApp strictly rejects WebM containers generated by Chrome browsers.
      // We fallback to sending it as a playable document attachment so it successfully delivers.
      if (determinedType === 'audio' && (media_url?.includes('.webm') || media_url?.includes('.ogg'))) {
        determinedType = 'document'
      }

      const payload: any = {
        messaging_product: 'whatsapp',
        to: phone_number.replace('+', ''), // Meta requires phone without +
        type: determinedType
      }

      if (payload.type === 'text') {
        payload.text = { body: message }
      } else {
        // e.g. type 'image', 'document', or 'audio'
        payload[payload.type] = { link: media_url }
        
        // Add a filename if we are sending a forced voice note document
        if (payload.type === 'document' && media_url?.includes('-voicenote.')) {
          payload.document.filename = 'VoiceNote.ogg'
        }

        // Meta WhatsApp API rejects 'caption' on audio messages
        if (message && payload.type !== 'audio') {
          payload[payload.type].caption = message
        }
      }

      const metaRes = await fetch(`https://graph.facebook.com/v20.0/${whatsapp_phone_id}/messages`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${whatsapp_token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      })

      if (!metaRes.ok) {
        const errorText = await metaRes.text()
        console.error(`[reply] Meta API Error: ${errorText}`)
        throw new Error(`Meta API Error: ${errorText}`)
      }

      // Capture provider_message_id to support delivery ticks
      const metaData = await metaRes.json()
      const wamid = metaData?.messages?.[0]?.id
      
      if (wamid) {
        await supabaseAdmin
          .from('messages')
          .update({ provider_message_id: wamid })
          .eq('id', msg.id)
      }
    } 
    // Priority 2: Legacy n8n Webhook Fallback
    else if (n8n_reply_webhook_url) {
      console.log(`[reply] Sending via n8n fallback for org: ${orgId}`)
      await fetch(n8n_reply_webhook_url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ phone_number, message, media_url, media_type, direction: 'outgoing', timestamp, platform }),
      })
    }

    return NextResponse.json({ success: true, message_id: msg.id })
  } catch (err: any) {
    const error = err?.message || String(err || 'Unknown error')
    return NextResponse.json({ error }, { status: 500 })
  }
}